# Highlight.io services for the hobby deployment.
services:
    backend:
        container_name: backend
        image: ${BACKEND_IMAGE_NAME-ghcr.io/highlight/highlight-backend:latest}
        # build:
        #     dockerfile: ./docker/backend.Dockerfile
        #     context: ..
        restart: on-failure
        ports:
            - '0.0.0.0:8082:8082'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.highlightio-be.rule=Host(`highlightio-be.tokenize-dev.com`)"
            - "traefik.http.services.highlightio-be.loadbalancer.server.port=8082"
            - "traefik.http.routers.highlightio-be.entrypoints=websecure"
        volumes:
            - highlight-data:/highlight-data
            - ../backend/env.enc:/build/env.enc
            - ../backend/env.enc.dgst:/build/env.enc.dgst
            - ../backend/localhostssl/server.key:/build/localhostssl/server.key
            - ../backend/localhostssl/server.crt:/build/localhostssl/server.crt
        env_file: .env

    frontend:
        container_name: frontend
        image: highlight-frontend:local
        build:
            dockerfile: ./docker/frontend.Dockerfile
            context: ..
            args:
                REACT_APP_AUTH_MODE: password
                REACT_APP_DISABLE_ANALYTICS: ${REACT_APP_DISABLE_ANALYTICS}
                DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
                SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
        restart: on-failure
        volumes:
            - ../backend/localhostssl/server.key:/etc/ssl/private/ssl-cert.key
            - ../backend/localhostssl/server.pem:/etc/ssl/certs/ssl-cert.pem
        ports:
            - '0.0.0.0:3000:3000'
            - '0.0.0.0:6006:6006'
            - '0.0.0.0:8080:8080'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.highlightio.rule=Host(`highlightio.tokenize-dev.com`)"
            - "traefik.http.services.highlightio.loadbalancer.server.port=3000"
            - "traefik.http.routers.highlightio.entrypoints=websecure"
        env_file: .env

    traefik:
        container_name: traefik
        restart: on-failure
        build:
            context: "../traefik"
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            # - "0.0.0.0:8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - traefik-ssl-certs:/ssl-certs

volumes:
    highlight-data:
    traefik-ssl-certs:
